# s1=input("ENter a first string:")
# s2=input("ENter a second string:")
# h1=set(s1.split())
# h2=set(s2.split())
# print(h1)
# print(h2)
# c1=len(h1)
# c2=len(h2)
# print(c1+c2)

sent1=input()
sent2=input()
h1 = set(sent1.split())
h2 = set(sent2.split())
s1=len(h1)
s2=len(h2)
print(s1+s2)